driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
  driver_config:
    network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-15.10
  run_list:
  - recipe[apt]
- name: centos-5.11
- name: centos-6.7
- name: centos-7.2
- name: opensuse-13.2
  driver:
    box: opensuse-13.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
  attributes: {java: {install_flavor: openjdk, jdk_version: 7, openjdk_packages: [ "java-1_7_0-openjdk", "java-1.7.0-openjdk-devel" ], set_etc_environment: true }}
  run_list:
    - recipe[zypper]

suites:
- name: helloworld_example
  run_list: ["recipe[test::helloworld_example]"]
  attributes:
    java:
      install_flavor: oracle
      jdk_version: 8
      set_etc_environment: true
      oracle:
        accept_oracle_download_terms: true
